[package]
name = "mere"
version = "0.1.0"
authors = ["Douglas Lau <doug.lau@state.mn.us>"]
description = "A real-time directory mirroring service"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/mnit-rtmc/mere"
repository = "https://github.com/mnit-rtmc/mere"
readme = "README.md"
edition = "2018"

[dependencies]
env_logger = "0.7.0"
log = "0.4.8"
ssh2 = "0.4.0"
whoami = "0.5.3"
