[package]
name = "mere"
version = "0.1.1"
authors = ["Douglas Lau <doug.lau@state.mn.us>"]
description = "A low-latency directory mirroring service"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/mnit-rtmc/mere"
repository = "https://github.com/mnit-rtmc/mere"
readme = "README.md"
edition = "2018"

[dependencies]
log = "0.4.8"
notify = "4.0.13"
whoami = "0.5.3"

[dependencies.ssh2]
version = "0.4.0"
features = ["vendored-openssl"]

[dependencies.env_logger]
version = "0.7.0"
default_features = false
features = ["atty", "humantime"]
